# Generated by Django 5.0.6 on 2024-06-21 19:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='M', max_length=3)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shirts/')),
            ],
            options={
                'ordering': ('model', 'size'),
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(44)])),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoes/')),
            ],
            options={
                'ordering': ('model', 'size'),
            },
        ),
        migrations.CreateModel(
            name='User_Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='User_Avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
